#!/bin/bash

if [ -e /var/lib/homebridge/disable-auto-update ]; then
  echo "Auto update disabled..."
  exit 0
fi

/usr/local/bin/docker-compose -f /home/hoobs/docker-compose.yml --project-directory /home/hoobs pull
/home/hoobs/start.sh
/usr/bin/docker system prune -f
