#!/bin/bash

MODE=""
ARCH=""
NODE="stable"
CONNECT="false"
DOCKER="false"

usage()
{
    echo ""
    echo "help: image [command] [-n | --node tag] [-c | --container]"
    echo "    Display information about builtin commands."
    echo ""
    echo "    This is used to build the HOOBS SD card images."
    echo ""
    echo "    Note:"
    echo "        This script requires elevated permissions, please run this with"
    echo "        SUDO or ROOT privileges."
    echo ""
    echo "    Commands:"
    echo "        build                    builds all architectures"
    echo "        build armv7l             builds the armv7l architecture"
    echo "        build armv6l             builds the armv6l architecture"
    echo "        build connect            builds the hoobs connect interface"
    echo "        clean                    cleans the work and deploy directories"
    echo ""
    echo "    Options:"
    echo "        -c, --container          build using a docker container"
    echo "        -n, --node [tag]         node version tag (stable, lts, latest)"
    echo "        -h, --help               displays this help menu"
    echo ""
    echo "    Returns:"
    echo "        Returns success unless the install fails."
    echo ""
}

line()
{
    echo "--------------------------------------------------------------------------------------------------------------------------"
}

while [ "$1" != "" ]; do
    case $1 in
        build )             MODE="build"
                            ;;

        clean )             MODE="clean"
                            ;;

        armv7l )            ARCH="armv7l"
                            ;;

        armv6l )            ARCH="armv6l"
                            ;;

        connect )           CONNECT="true"
                            ;;

        -n | --node )       shift
                            NODE=$1
                            ;;

        -c | --container)   DOCKER="true"
                            ;;

        -h | --help )       usage
                            exit
                            ;;

        * )                 usage
                            exit
    esac

    shift
done

cd "$(dirname "$0")"

case $MODE in
    "build")    if [[ "$CONNECT" = "true" ]]; then
                    if [[ -f "../hoobs-connect/.gitignore" ]]; then
                        cd ../hoobs-connect/

                        rm -f ./builds/wifi-connect-hoobs.tar.gz
                        cp -R ./ui ./builds/
                        cd ./builds/
                        tar -cvzf ui.tar.gz ./ui/*
                        mkdir ./wifi-connect-hoobs
                        mv ./ui ./wifi-connect-hoobs/
                        mv ./ui.tar.gz ./wifi-connect-hoobs/
                        tar -cvzf wifi-connect-hoobs.tar.gz ./wifi-connect-hoobs/*
                        chmod 755 ./wifi-connect-hoobs.tar.gz
                        rm -fR ./wifi-connect-hoobs
                    else
                        echo "You need to clone the \"hoobs-connect\" repository at the same level as \"hoobs-core\"."
                        echo "Run these commands."
                        echo "    cd ../"
                        echo "    git clone https://github.com/hoobs-org/hoobs-connect.git"
                    fi
                else
                    case $ARCH in
                        "armv7l")   case $NODE in
                                        "stable")   echo ""
                                                    echo "Fetching Updates"
                                                    line

                                                    git pull

                                                    line
                                                    echo ""
                                                    echo ""
                                                    echo "Building Current ARM V7"
                                                    line

                                                    if [[ "$DOCKER" = "true" ]]; then
                                                        ./build-docker.sh -c armv7l
                                                    else
                                                        sudo ./build.sh -c armv7l
                                                    fi

                                                    ;;

                                        "lts")      echo ""
                                                    echo "Fetching Updates"
                                                    line

                                                    git pull

                                                    line
                                                    echo ""
                                                    echo ""
                                                    echo "Building LTS ARM V7 Node LTS"
                                                    line

                                                    if [[ "$DOCKER" = "true" ]]; then
                                                        ./build-docker.sh -c armv7lts
                                                    else
                                                        sudo ./build.sh -c armv7lts
                                                    fi

                                                    ;;

                                        "latest")   echo ""
                                                    echo "Fetching Updates"
                                                    line

                                                    git pull

                                                    line
                                                    echo ""
                                                    echo ""
                                                    echo "Building Development ARM V7 Latest Node"
                                                    line

                                                    if [[ "$DOCKER" = "true" ]]; then
                                                        ./build-docker.sh -c armv7latest
                                                    else
                                                        sudo ./build.sh -c armv7latest
                                                    fi

                                                    ;;

                                        * )         usage
                                                    ;;
                                    esac

                                    ;;

                        "armv6l")   case $NODE in
                                        "stable")   echo ""
                                                    echo "Fetching Updates"
                                                    line

                                                    git pull

                                                    line
                                                    echo ""
                                                    echo ""
                                                    echo "Building Current ARM V6"
                                                    line

                                                    if [[ "$DOCKER" = "true" ]]; then
                                                        ./build-docker.sh -c armv6l
                                                    else
                                                        sudo ./build.sh -c armv6l
                                                    fi

                                                    ;;

                                        "lts")      echo ""
                                                    echo "Node LTS is not available for ARM 6"
                                                    echo ""
                                                    ;;

                                        "latest")   echo ""
                                                    echo "Node Latest is not available for ARM 6"
                                                    echo ""
                                                    ;;

                                        * )         usage
                                                    ;;
                                    esac

                                    ;;

                        * )         echo ""
                                    echo "Fetching Updates"
                                    line

                                    git pull

                                    line
                                    echo ""
                                    echo ""

                                    echo "Building Current ARM V7"
                                    line

                                    if [[ "$DOCKER" = "true" ]]; then
                                        ./build-docker.sh -c armv7l
                                    else
                                        sudo ./build.sh -c armv7l
                                    fi

                                    line
                                    echo ""
                                    echo ""
                                    echo "Building Current ARM V6"

                                    if [[ "$DOCKER" = "true" ]]; then
                                        ./build-docker.sh -c armv6l
                                    else
                                        sudo ./build.sh -c armv6l
                                    fi

                                    line
                                    echo ""
                                    echo ""
                                    echo "Building LTS ARM V7 Node LTS"

                                    if [[ "$DOCKER" = "true" ]]; then
                                        ./build-docker.sh -c armv7lts
                                    else
                                        sudo ./build.sh -c armv7lts
                                    fi

                                    line
                                    echo ""
                                    echo ""
                                    echo "Building Development ARM V7 Latest Node"

                                    if [[ "$DOCKER" = "true" ]]; then
                                        ./build-docker.sh -c armv7latest
                                    else
                                        sudo ./build.sh -c armv7latest
                                    fi

                                    line
                                    echo ""
                                    ;;
                    esac
                fi

                ;;

    "clean")    rm -fR ./work
                rm -fR ./deploy
                ;;

    * )         usage
                ;;
esac
