#!/bin/bash

MODEL=$(tr -d '\0' </proc/device-tree/model)
printf "$MODEL\n"

IP=$(hostname -I)

printf "\n\n*** HOOBS - Homebridge Out Of The Box ***\n"

printf "\n"
printf "  _    _    ____     ____    ____     _____\n"
printf " | |  | |  / __ \   / __ \  |  _ \   / ____|\n"
printf " | |__| | | |  | | | |  | | | |_) | | (___         ___    _ __    __ _\n"
printf " |  __  | | |  | | | |  | | |  _ <   \___ \       / _ \  |  __|  / _  |\n"
printf " | |  | | | |__| | | |__| | | |_) |  ____) |  _  | (_) | | |    | (_| |\n"
printf " |_|  |_|  \____/   \____/  |____/  |_____/  (_)  \___/  |_|     \__, |\n"
printf "                                                                  __/ |\n"
printf "                                                                 |___/\n"
printf "\n"

printf "To configure HOOBS browse to the one of the following addresses from another device on your network:" | fold -s
printf "\n\n"
printf "* http://$(hostname).local\n"

for ip in $IP; do
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf "* http://$ip\n"
  else
    printf "* http://[$ip]\n"
  fi
done
