#!/bin/bash

set -e

CURRENT_ARCH=$(uname -m)
BUILD_ARCH=$(cat /etc/hoobs-arch)

echo "Current: $CURRENT_ARCH"
echo "Build: $BUILD_ARCH"

if [ $CURRENT_ARCH != $BUILD_ARCH ]; then
        echo "Rebuild Required"
        cd "/usr/local/lib/node_modules"
        /usr/local/bin/npm --unsafe-perm rebuild
        echo $(uname -m) | sudo tee /etc/hoobs-arch
fi

