#!/bin/bash

IP=$(hostname -I)

printf "\n*** HOOBS Build Server ***\n"

printf "\n"
printf "   _    _  ____   ____  ____   _____   \n"
printf "  | |  | |/ __ \ / __ \|  _ \ / ____|  \n"
printf "  | |__| | |  | | |  | | |_) | (___    \n"
printf "  |  __  | |  | | |  | |  _ < \___ \   \n"
printf "  | |  | | |__| | |__| | |_) |____) |  \n"
printf "  |_|  |_|\____/ \____/|____/|_____/   \n"
printf "                                       \n"

printf "* ssh hoobs@$(hostname)\n"

for ip in $IP; do
  if [[ $ip =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    printf "* ssh hoobs@$ip\n"
  else
    printf "* ssh hoobs@[$ip]\n"
  fi
done
